#!/bin/bash
cd $home && cd HACKING-TOOLS && cd LIST
apt install python
git clone https://github.com/Z4nzu/hackingtool.git
chmod 777 hackingtool  
cd hackingtool
pip install -r requirement.txt
bash install.sh
python hackingtool.py
