#!/bin/bash
cd $home && cd HACKING-TOOLS && cd LIST
pkg install git
pkg install python2
pkg install ruby
git clone https://github.com/Sanju8943/Malicious-Programme
cd Malicious
pip2 install -r requirements.txt
python2 malicious.py
